### ISSUE TITLE
When I am using custom fonts and generate PDF using "instance.jsonToPDFBase64(json)" return key is not working

### ISSUE THREAD

**Issue by tejas-webmavens** [lavrton/polotno-node#1]
When I am creating my design using custom fonts. and creating the PDF using instance.jsonToPDFBase64(json) function then it's converting return into the \n like below image. I also checked with PNG as well and it gives the same error.

![image](https://user-images.githubusercontent.com/20989124/114695142-e4f62c80-9d38-11eb-8a86-d7b930ef296f.png)

Below is JSON for reference which I am using

[sample-polotno.json.txt](https://github.com/lavrton/polotno-node/files/6310126/sample-polotno.json.txt)

**Comment by lavrton** [comment]
Do you mean `\n` is not correct and you should have just a new line?

As I can see in your json, new line is escaped `\\n`. So the output looks correct for me from such a json.

**Comment by tejas-webmavens** [comment]
thanks. Found the issue in my JSON.
